name: Build and Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release

  test-and-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: cargo test --verbose

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run code coverage
        run: cargo tarpaulin --out Xml, Html --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true

  github-pages:
    needs: test-and-coverage
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.PTA }}
          publish_dir: ./TestResults/CoverageReport
          publish_branch: gh-pages
          commit_message: "Update code coverage report"